module.exports = [
  "Anglais",
  "Faire un CV",
  "Faire une lettre de motivation",
  "Se présenter",
  "Parler en public",
  "Informatique",
  "Relation client",
  "Démarches administrative",
  "Confiance en soi",
  "Suite Office",
  "Bâtiment",
  "Sécurité",
  "Reconversion",
  "Petite enfance",
  "Enseignement",
  "Cuisine",
  "Service bar",
  "Plomberie",
  "Peinture",
  "Freelance"
];
